# -*- coding: utf-8 -*-
# Shared structs for PolyIOP
import torch
import torch.nn.functional as F
from typing import Any, List, Tuple
from ....arithmetic.src.virtual_polynomial import VirtualPolynomial
from ....fields import fr

# ---------------------------------------------------------------------------
# Barycentric interpolation utilities
# ---------------------------------------------------------------------------

def barycentric_weights(points: torch.Tensor) -> torch.Tensor:
    """
    Compute barycentric weights w_j = 1 / ∏_{i≠j} (x_j - x_i) for points x_j.
    Uses batch inversion to compute all reciprocals efficiently.
    """
    weights = []
    n = len(points)
    for j, xj in enumerate(points):
        # product over i != j of (xj - xi)
        prod = None
        for i, xi in enumerate(points):
            if i == j:
                continue
            term = F.sub_mod(xj, xi)
            prod = term if prod is None else (F.mul_mod(prod, term, inplace = True))
        weights.append(prod if prod is not None else fr.one())
    weights = torch.stack(weights, dim=0)
    # Invert all weights in place
    F.inv_mod(weights, inplace = True)
    return weights

class IOPProof:
    """
    An IOP proof consists of:
      - `point`: the evaluation point generated by the transcript.
      - `proofs`: prover-to-verifier messages for each round.
    """

    def __init__(self, point: List[torch.Tensor], proofs: List["IOPProverMessage"]):
        self.point: List[torch.Tensor] = [] if point is None else list(point)
        self.proofs: List[IOPProverMessage] = [] if proofs is None else list(proofs)

    @classmethod
    def default(cls) -> "IOPProof":
        return cls()


class IOPProverMessage:
    """
    A prover message for a given round: list of univariate evaluations.
    """

    def __init__(self, evaluations: torch.Tensor = None):
        self.evaluations: torch.Tensor = torch.empty(0) if evaluations is None else evaluations


class IOPProverState:
    """
    Attributes:
      - challenges: List of challenges r_1, r_2, ...
      - round: Current round index (0-based, but logic follows the Rust flow)
      - poly: VirtualPolynomial (with .aux_info, .products, .flattened_ml_extensions)
      - extrapolation_aux: Precomputed (points, weights) per degree for barycentric extrapolation
    """

    def __init__(self, poly: VirtualPolynomial):
        self.challenges: List[torch.Tensor] = []
        self.round: int = 0
        self.poly: VirtualPolynomial = poly
        self.extrapolation_aux: List[Tuple[torch.Tensor, torch.Tensor]] = []

    @staticmethod
    def prover_init(polynomial: VirtualPolynomial) -> "IOPProverState":
        """
        Initialize prover state to argue the sum of the polynomial over {0,1}^n.
        """
        if polynomial.num_variables == 0:
            # Mirror Rust: attempting to prove a constant is invalid here
            raise ValueError("InvalidParameters: attempt to prove a constant.")
        poly: IOPProverState = IOPProverState(polynomial)
        for degree in range(1, poly.poly.max_degree):
            points = torch.stack([fr.from_int(i) for i in range(0, 1 + degree)], dim=0)
            weights = barycentric_weights(points)
            poly.extrapolation_aux.append((points, weights))

        return poly

class IOPVerifierState:
    """
    Notes:
      - `polynomials_received`: per-round univariate polynomials in evaluation form.
      - `challenges`: verifier-sampled randomness per round.
    """

    def __init__(self, num_vars: int, max_degree: int):
        self.round: int = 1
        self.num_vars: int = num_vars
        self.max_degree: int = max_degree
        self.finished: bool = False
        self.polynomials_received: List[List[torch.Tensor]] = []
        self.challenges: List[torch.Tensor] = []
    
    
